
private:

    Adafruit_ADS1115 ads;
    class LiquidCrystal_I2C* lcd;
    uint8_t _IdCliente;
    uint8_t _portSpeed;
    uint8_t _mydelay;
    uint8_t _pin[23];
    uint8_t _pinsInputDigital;
    uint8_t _pinsOutputDigital;
    uint16_t INPUT_REG[4];
    uint16_t HOLDING_REG[17];
    uint8_t INPUTS;
    uint8_t lastStateInputs = 0;
    unsigned long timeIni=0;
    bool timeMeasEn = false;
    uint8_t LATCH = 0;
    uint8_t MASK = 0;
    bool fIDLE = false;
    uint8_t previous_state_B;
    uint8_t previous_state_C;
    uint8_t index = 0;
    uint16_t StartingAddress16;
    uint16_t Quantity16;
    uint8_t ByteCount;
    static M4x4_R3* theM4x4_R3;
    float x = 1.2345;
    float y = 6.789;
    const uint8_t PWMmax = 255;
    const uint16_t ADmax = 32767;
    bool saveCounters = false;
    uint8_t modeAnaInp = 0;
    uint16_t corrAnaInpToMax;
    uint16_t corrAnaOutTo10V;
    uint8_t IntTimeVal;
    byte RXBUF[33];
    byte TXBUF[33];
    const uint8_t bitmask[4] = {0x01,0x02,0x04,0x08};
    bool c[4]={0,0,0,0};
    unsigned long counter[4]={0,0,0,0};
    unsigned long savedValue[4]={0,0,0,0};
    bool guardar_cont[4]={0,0,0,0};
    uint16_t countUpDown;
    uint16_t releTime1 = 0;
    uint16_t releTime2 = 0;
    uint16_t releTime3 = 0;
    uint16_t releTime4 = 0;
    uint16_t ellapsedTime1 = 0;
    uint16_t ellapsedTime2 = 0;
    uint16_t ellapsedTime3 = 0;
    uint16_t ellapsedTime4 = 0;
    bool rele1on = false;
    bool rele2on = false;
    bool rele3on = false;
    bool rele4on = false;
    uint8_t countLcd = 0;
    uint8_t countDwnLcd = 10;
    bool stateLcd = true;
    bool refreshLcd = false;
    bool firstpress = false;
